-- =============================================================================
-- Migration 5: Weekly Pre-Order Architecture — Cleanup
-- =============================================================================
-- Drops deprecated columns, functions, triggers, tables, indexes, and
-- tightens CHECK constraints to remove wallet/balance/topup/stock references.
-- Run AFTER data migration (migration 4) has completed.
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. DROP deprecated COLUMNS
-- ---------------------------------------------------------------------------

-- orders.meal_period (meals now tracked on order_items or weekly_orders)
ALTER TABLE orders DROP COLUMN IF EXISTS meal_period;

-- orders.paymongo_payment_id (payments table handles external refs)
ALTER TABLE orders DROP COLUMN IF EXISTS paymongo_payment_id;

-- products.stock_quantity (stock tracking removed entirely)
ALTER TABLE products DROP COLUMN IF EXISTS stock_quantity;

-- ---------------------------------------------------------------------------
-- 2. UPDATE CHECK CONSTRAINTS — remove 'balance' and 'paymongo' from payment methods
-- ---------------------------------------------------------------------------
-- Constraint names are auto-generated by Postgres from inline CHECKs.

-- orders.payment_method: was ('cash','balance','gcash','paymaya','card','paymongo')
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_payment_method_check;
ALTER TABLE orders ADD CONSTRAINT orders_payment_method_check
  CHECK (payment_method IN ('cash', 'gcash', 'paymaya', 'card'));

-- payments.method: was ('cash','gcash','paymaya','card','paymongo','balance')
ALTER TABLE payments DROP CONSTRAINT IF EXISTS payments_method_check;
ALTER TABLE payments ADD CONSTRAINT payments_method_check
  CHECK (method IN ('cash', 'gcash', 'paymaya', 'card'));

-- payments.type: was ('payment','refund','topup')
ALTER TABLE payments DROP CONSTRAINT IF EXISTS payments_type_check;
ALTER TABLE payments ADD CONSTRAINT payments_type_check
  CHECK (type IN ('payment', 'refund'));

-- cart_state.payment_method: was ('cash','gcash','balance')
ALTER TABLE cart_state DROP CONSTRAINT IF EXISTS cart_state_payment_method_check;
ALTER TABLE cart_state ADD CONSTRAINT cart_state_payment_method_check
  CHECK (payment_method IN ('cash', 'gcash', 'paymaya', 'card'));

-- ---------------------------------------------------------------------------
-- 3. DROP deprecated TRIGGERS
-- ---------------------------------------------------------------------------

-- validate_cart_item_max_advance_trigger already dropped in migration 2
-- but ensure it's gone
DROP TRIGGER IF EXISTS validate_cart_item_max_advance_trigger ON cart_items;

-- Wallet updated_at trigger
DROP TRIGGER IF EXISTS update_wallets_updated_at ON wallets;

-- Block legacy writes trigger (references transactions_legacy)
DROP TRIGGER IF EXISTS trg_block_legacy_writes ON transactions_legacy;

-- ---------------------------------------------------------------------------
-- 4. DROP deprecated FUNCTIONS
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS deduct_balance_with_payment(
  p_parent_id UUID,
  p_expected_balance NUMERIC(10,2),
  p_amount NUMERIC(10,2),
  p_order_ids UUID[],
  p_order_amounts NUMERIC(10,2)[]
);

DROP FUNCTION IF EXISTS credit_balance_with_payment(
  p_parent_id UUID,
  p_amount NUMERIC(10,2),
  p_type TEXT,
  p_method TEXT,
  p_reference_id TEXT,
  p_order_id UUID,
  p_external_ref TEXT,
  p_paymongo_refund_id TEXT,
  p_paymongo_payment_id TEXT,
  p_paymongo_checkout_id TEXT,
  p_original_payment_id UUID
);

DROP FUNCTION IF EXISTS increment_stock(
  p_product_id UUID,
  p_quantity INTEGER
);

DROP FUNCTION IF EXISTS decrement_stock(
  p_product_id UUID,
  p_quantity INTEGER
);

DROP FUNCTION IF EXISTS block_legacy_writes();

DROP FUNCTION IF EXISTS validate_cart_item_max_advance();

DROP FUNCTION IF EXISTS get_todays_menu();

DROP FUNCTION IF EXISTS get_menu_for_day(target_day INTEGER);

DROP FUNCTION IF EXISTS is_menu_available(check_date DATE);

DROP FUNCTION IF EXISTS get_dashboard_stats();

-- merge_order_items does NOT exist — skipped per schema research

-- ---------------------------------------------------------------------------
-- 5. DROP deprecated RLS POLICIES on wallets
-- ---------------------------------------------------------------------------

DROP POLICY IF EXISTS "Users can view their own wallet" ON wallets;
DROP POLICY IF EXISTS "Only system can insert wallets" ON wallets;
DROP POLICY IF EXISTS "Only system can update wallets" ON wallets;
DROP POLICY IF EXISTS "Users can view own wallet" ON wallets;
DROP POLICY IF EXISTS "System manages wallets" ON wallets;
DROP POLICY IF EXISTS "Admin manages wallets" ON wallets;

-- ---------------------------------------------------------------------------
-- 6. DROP deprecated TABLES
-- ---------------------------------------------------------------------------

DROP TABLE IF EXISTS topup_sessions CASCADE;
DROP TABLE IF EXISTS wallets CASCADE;
DROP TABLE IF EXISTS transactions_legacy CASCADE;

-- ---------------------------------------------------------------------------
-- 7. DROP deprecated INDEXES
-- ---------------------------------------------------------------------------

DROP INDEX IF EXISTS idx_products_stock_quantity;
DROP INDEX IF EXISTS idx_orders_paymongo_payment_id;

-- ---------------------------------------------------------------------------
-- 8. Clean up any 'balance' or 'paymongo' values in existing data
-- ---------------------------------------------------------------------------

-- Convert any existing 'balance' payment_method orders to 'cash' (safety net)
UPDATE orders SET payment_method = 'cash'
WHERE payment_method IN ('balance', 'paymongo');

UPDATE payments SET method = 'cash'
WHERE method IN ('balance', 'paymongo');

UPDATE cart_state SET payment_method = 'cash'
WHERE payment_method IN ('balance');

-- Remove topup payment records
DELETE FROM payments WHERE type = 'topup';

-- ---------------------------------------------------------------------------
-- 9. Update consolidated schema comment
-- ---------------------------------------------------------------------------

COMMENT ON TABLE orders IS 'Daily orders — now linked to weekly_orders via weekly_order_id';
COMMENT ON TABLE products IS 'Menu items — stock tracking removed';

COMMIT;
